# Generated by Django 3.2.14 on 2023-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
